import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import ThemeRegistry from "@/theme/ThemeRegistry";
import QueryProvider from "@/theme/QueryProvider";
import Navbar from "./Common/Navbar/Navbar";
import Script from "next/script";
import Footer from "./Common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Hiflux UK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable}`}
    >
      <head>
        <script
          data-cfasync="false"
          type="text/javascript"
          src="https://cdn.seoplatform.io/injector.js?websiteId=28611"
        />
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
        (function(c,l,a,r,i,t,y){
            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
        })(window, document, "clarity", "script", "y5wirsyo68");
      `,
          }}
        />
      </head>
      <body>
        <QueryProvider>
          <ThemeRegistry>
            {" "}
            <Navbar />
            {children}
            <Script
              src="https://www.googletagmanager.com/gtag/js?id=G-VES6DYGCYH"
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-VES6DYGCYH');
  `}
            </Script>
            <Footer />
          </ThemeRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
