import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import ThemeRegistry from "@/theme/ThemeRegistry";
import QueryProvider from "@/theme/QueryProvider";
import Navbar from "./Common/Navbar/Navbar";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Hiflux UK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable}`}
    >
      <head>
        <script
          data-cfasync="false"
          type="text/javascript"
          src="https://cdn.seoplatform.io/injector.js?websiteId=28611"
        />
      </head>
      <body>
        <QueryProvider>
          <ThemeRegistry>
            {" "}
            <Navbar />
            {children}
            <Script
              src="https://www.googletagmanager.com/gtag/js?id=G-VES6DYGCYH"
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-VES6DYGCYH');
  `}
            </Script>
          </ThemeRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
